-- Sample T2T SQL for testing lineage parser
-- This is the SELECT portion from a MERGE INTO statement

SELECT
    A.CONTRACT_ID,
    A.CONTRACT_NUMBER,
    B.CUSTOMER_NAME,
    UPPER(B.CUSTOMER_TYPE) AS CUSTOMER_TYPE_CD,
    CASE
        WHEN A.STATUS_CODE = 'A' THEN 'ACTIVE'
        WHEN A.STATUS_CODE = 'C' THEN 'CLOSED'
        ELSE 'UNKNOWN'
    END AS STATUS_DESC,
    NVL(C.BRANCH_NAME, 'DEFAULT') AS BRANCH_NAME,
    A.AMOUNT + NVL(A.FEE_AMOUNT, 0) AS TOTAL_AMOUNT,
    SYSDATE AS LOAD_DATE,
    'BATCH_001' AS BATCH_ID,
    SUM(D.PAYMENT_AMOUNT) AS TOTAL_PAYMENTS,
    ROW_NUMBER() OVER (PARTITION BY A.CONTRACT_ID ORDER BY A.EFFECTIVE_DATE DESC) AS ROW_NUM
FROM
    STG_CONTRACTS A
    INNER JOIN STG_CUSTOMERS B ON A.CUSTOMER_ID = B.CUSTOMER_ID
    LEFT JOIN DIM_BRANCH C ON A.BRANCH_CODE = C.BRANCH_CODE
    LEFT JOIN STG_PAYMENTS D ON A.CONTRACT_ID = D.CONTRACT_ID
WHERE
    A.EFFECTIVE_DATE >= TRUNC(SYSDATE) - 365
    AND B.CUSTOMER_STATUS = 'ACTIVE'
GROUP BY
    A.CONTRACT_ID,
    A.CONTRACT_NUMBER,
    B.CUSTOMER_NAME,
    B.CUSTOMER_TYPE,
    A.STATUS_CODE,
    C.BRANCH_NAME,
    A.AMOUNT,
    A.FEE_AMOUNT,
    A.EFFECTIVE_DATE
